import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import ThemeProvider from "@/components/ThemeProvider";
import SearchConProvider from "./context/searchContext";
import Navbar from "@/components/Navbar";
import ThemeToggle from "@/components/ThemeToggle";
import ToastProvider from "@/components/ToastProvider";
import Providers from './context/Provider'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* https://res.cloudinary.com/dcyn3ewpv/video/upload/v1767630846/cosmic-bg_gqcncx.mp4 */}
     
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ToastProvider />
        {/* Background Video */}
        <div className="fixed inset-0 -z-10 overflow-hidden">
          <video
            autoPlay
            muted
            loop
            playsInline
            className="absolute inset-0 h-full w-full object-cover"
            src="https://res.cloudinary.com/dcyn3ewpv/video/upload/v1767630846/cosmic-bg_gqcncx.mp4"
          >
          
            <source src="https://res.cloudinary.com/dcyn3ewpv/video/upload/v1767630846/cosmic-bg_gqcncx.mp4" type="video/mp4" />
          </video>

      
          <div className="absolute inset-0 bg-black/30" />
        </div>
        <Providers>
        <ThemeProvider>
          <SearchConProvider>
            <Navbar />
            <main>
              {children}
            </main>
            <div className="fixed bottom-6 right-6 z-50">
              <ThemeToggle />
            </div>
          </SearchConProvider>
        </ThemeProvider>
        </Providers>
        <Script src="https://sdk.cashfree.com/js/v3/cashfree.js" strategy="afterInteractive"/>
      </body>
    
    </html>
  );
}




